language: cpp

env:
  global:
    - LINUX_DIST=focal
    - CXX_FLAGS="-Wall -Wpedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    - RUN_TESTS=true

matrix:
  include:
    os: linux
    dist: focal
    sudo: true
    compiler: gcc
    addons:
      apt:
        packages:
          - gcc-9
          - g++-9
          - valgrind
          - cmake
        sources:
          - ubuntu-toolchain-r-test

before_install:
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v

script:
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DBUILD_TESTS=ON ..
  - make
  - ctest


